### ISSUE TITLE
No matching clause for goal: cmd(predicate(A,{'0'},{[]}),B)

### ISSUE THREAD

**Issue by pmoura** [SWI-Prolog/packages-ltx2htm#3]
A likely bug reported by the Logtalk linter:

```text
*     No matching clause for goal: cmd(predicate(A,{'0'},{[]}),B)
*       while compiling object latex2html4xpce
*       in file /Users/pmoura/lib/swipl/library/latex2html/sty_xpce.pl between lines 114-115
```

The clause is:

https://github.com/SWI-Prolog/packages-ltx2htm/blob/3cd904bfec8d2f209f2f8ab3d5813e4534742c1f/sty_xpce.pl#L114-L115

**Comment by JanWielemaker** [comment]
A false alarm.  It is defined in `sty_pldoc.pl`, but I cannot blame your linter not finding that considering the rather hacky way the final code base is assembled.   I guess it is either an argument to now allow this hacky way of loading or do the linting on the loaded image rather than on the source :smile: ,  I think we have different opinions :smiley_cat:

**Comment by pmoura** [comment]
Wouldn't declare the predicate as multifile make it clear?

**Comment by JanWielemaker** [comment]
Possibly.  It is old code just maintained to generate the documentation.  It works, so I won't touch it before it is broken :smile:
